version: 2

# Set up the build environment
build:
  image: latest

# Set up Python version and requirements
python:
  version: 3.12
  install:
    - requirements: requirements.txt  # Adjust the path if your requirements file is elsewhere
  system_packages: true  # If you need to install additional system packages

# Set up Sphinx documentation build
sphinx:
  configuration: docs/conf.py  # Path from the root of your project to your Sphinx configuration file

# Optionally, specify formats other than HTML you want your project to be available in
formats:
  - pdf
  - htmlzip

# Submodules settings, if your project has submodules
submodules:
  include: all  # Options are "all", "none", or specifying a list of submodules
